version: '3.8'

services:
  web:
    image: 192.168.100.29:5000/hansol/initicube:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
    restart: always

  ubuntu:
    image: 192.168.100.29:5000/hansol/initcube_test:1.0.3
    build:
      context: .
      dockerfile: ./Dockerfile.qatest
